name: order_it_2
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  animate_do: ^3.3.4
  flutter:
    sdk: flutter
  http: ^1.2.1
  internet_connection_checker: ^1.0.0+1
  lottie: ^3.1.2
  provider: ^6.1.2
  supabase: ^2.2.2
  supabase_flutter: ^2.5.6

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/animations/mobile_scrolling.json
    - assets/animations/plato_girando.json
    - assets/animations/waitress.json
    - assets/icons/Logo.png
    - assets/icons/logoSinLetras.png
    - assets/icons/apple_icon.png
    - assets/icons/facebook_icon.png
    - assets/icons/google_icon.png
